name: Push Event Workflow

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'
    
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - run: |
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
        echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_ENV
      
    - run: pytest ./tests/test_main.py
